FROM python:3.10-slim

ENV TZ=America/Chicago
ENV POETRY_VIRTUALENVS_CREATE=False
ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libpq5 libpq-dev curl libpcre3 libpcre3-dev git mime-support ssh watchman && \
    pip install -U --no-cache-dir pip poetry uwsgi pywatchman psycopg2 && \
    rm -Rf /root/.cache && \
    apt-get remove -y build-essential libpcre3-dev libpq-dev && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*
